# Generated by Django 3.0.4 on 2020-04-01 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('dev_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Device', primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('value', models.CharField(max_length=100)),
                ('device_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='websiteapp.Device')),
            ],
        ),
    ]
